
set(CMAKE_SYSTEM_NAME Generic)

set(CMAKE_C_COMPILER clang)
set(CMAKE_C_COMPILER_TARGET x86_64-uefi)
set(CMAKE_EXECUTABLE_SUFFIX_C .efi)
set(CMAKE_STATIC_LIBRARY_SUFFIX_C .lib)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_CXX_COMPILER_TARGET x86_64-uefi)
set(CMAKE_EXECUTABLE_SUFFIX_CXX .efi)
set(CMAKE_STATIC_LIBRARY_SUFFIX_CXX .lib)

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)
